---
title: "Alfabetizacion"
author: "Paloma"
date: "2/1/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE,}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, out.width = "100%")
```

```{r}
library(rio)
library(here)
library(tidyverse)
library(tidytext)
library(plotly)
```

```{r}
censo <- import(here("02_datos_limpios", "censo.RData"))
```

```{r}
taza_alfab <- censo %>% 
  rename(
    alfab_hombres15 = `h_>15`,
    alfab_mujeres15 = `m_>15`) %>% 
  select(depto, prov, municipio, starts_with("alfab")) %>% 
  pivot_longer(
    cols = -c(1:3),
    names_to = "sexo",
    values_to = "taza_alfab"
  ) %>% 
  mutate(sexo = 
           ifelse(str_detect(sexo, "hombres"), "Niños", "Niñas"),
         taza_alfab = round(taza_alfab, 2))
```

```{r}
taza_alfab %>% 
  mutate(depto = str_remove(depto, "Departamento de")) %>% 
  mutate(depto = fct_reorder(depto, taza_alfab)) %>% 
  ggplot(aes(depto, taza_alfab, color = sexo)) +
  geom_boxplot() +
  scale_color_manual(values = c("#d11141", "#00b159" ) ) +
  coord_flip() +
  scale_y_reverse() +
  theme_minimal() +
    labs(
    title = "Distribución de la taza de alfabetización por departamento,\npara niñas y niños mayores a 15 años ",
    caption = "Fuente: Censo 2012, INDEC",
    x= "",
    y = "Taza de alfabetización (%)"
  ) 
```

```{r}
taza_alfab %>% 
  mutate(sexo = fct_rev(sexo)) %>% 
  ggplot(aes(sexo, taza_alfab, group = municipio)) +
  geom_point(aes(color = sexo)) +
  scale_color_manual(values = c("#d11141", "#00b159")) +
  geom_line(color = "#ffc425") +
  facet_wrap(.~depto) +
  theme_minimal() +
  labs(title = "Taza de alfabetización en mayores de 15 años por municipio",
       x = "Niños vs. niñas",
       y = "Taza de alfabetización",
       caption = "Datos de INDEC") 

```

```{r}
taza_alfab_dif_prov <- taza_alfab %>% 
  pivot_wider(
    names_from = sexo,
    values_from = taza_alfab) %>% 
  mutate(dif_sexo = Niñas - Niños) %>% 
group_by(depto, prov) %>% 
  summarize(min = min(dif_sexo),
            media = mean(dif_sexo),
            max = max(dif_sexo),
            ) %>% 
  ungroup()

taza_alfab_dif_prov %>% 
  mutate(prov = reorder_within(prov, media, depto)) %>% 
  mutate(min = ifelse(min == media, NA, min)) %>% 
  ggplot(aes(x = prov, y = media)) +
  geom_point(shape = 15) +
  geom_errorbar(aes(ymin = min, ymax = max))+
  facet_wrap(.~depto, scales = "free_y") +
  geom_hline(aes(yintercept  = 0)) +
  coord_flip() +
  scale_y_reverse() +
  theme_minimal() +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  labs(
    title = "Diferencia promedio entre la taza de alfabetización de niñas y niños \nmayores a 15 años por provincia",
    subtitle = "Fuente: Censo 2012",
    x = "Provincia",
    y = "Diferencia promedio",
    captions = "Las barras representan la diferencia mínima y máxima por provincia"
  )
```

```{r}
lolilop <- taza_alfab %>% 
  group_by(depto, prov, sexo) %>% 
  summarize(media_alfab = mean(taza_alfab)) %>% 
  ungroup() %>% 
  mutate(prov = reorder_within(prov, media_alfab, depto)) %>% 
  pivot_wider(
    names_from = sexo,
    values_from = media_alfab) %>% 
  ggplot() +
  geom_segment(aes(x = prov, xend = prov, y = Niñas, yend = Niños), color = "#ffc425") +
  geom_point(aes(x = prov, y = Niñas), color = "#d11141", size = 2) +
  geom_point(aes(x = prov, y = Niños), color = "#00b159", size = 2) +
  coord_flip() +
  facet_wrap(.~depto, scale = "free_y") +
  theme_minimal() +
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  labs(
    title = "Taza de alfabetización promedio por provincia, \npara niñas y niños mayores a 15 años ",
    subtitle = "En rojo la taza para niñas, en verde la taza para niños",
    caption = "Fuente: Censo 2012, INDEC",
    x= "Provincias",
    y = ""
  ) 

ggplotly(lolilop)
```


